AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Layout/LineLength:
  Max: 120

convention:Style/WordArray:
  Enabled: false

Style/Documentation:
    Enabled: false

convention:Metrics/MethodLength:
  Enabled: false
